#!/bin/bash

# export DOCKER_HOST="ssh://ajones@aj-server.local"

export dirname=${PWD##*/} 

case $1 in
    code )
        uri=$(python -c "import json; desc = json.dumps({'containerName': '/$dirname', 'settings': {'host':'ssh://aj-server.local'}}); print(f'vscode-remote://attached-container+{desc.encode().hex()}/code')")
        code --folder-uri "$uri" ;;
    notebook )
        open -t "http://localhost:5000/noterminal" ;; 
    notebooks )
        notebooks="$(docker exec -i $dirname find . -maxdepth 1 -name '.*.ipynb' -printf '%f\n')"
        echo "$notebooks" | xargs -I % open "http://localhost:5000/notebooks/%" ;;
    build ) 
        docker build docker -t $dirname ;;
    run )
        ssh aj-server.local mkdir -p /home/ajones/code/$dirname
        docker run -td --name $dirname -v /home/ajones/code/$dirname:/code $dirname:latest ;;
    logs )
        docker logs $dirname ;;
    stop )
        docker stop $dirname ;;
    start )
        docker start $dirname ;;
    restart )
        docker restart $dirname ;;
    rm )
        docker stop $dirname
        docker rm $dirname ;;
    * ) 
        echo "No command matching '$1'"
esac
