package:
    name: torchcule
    version: 0.1

source: 
    path: ..

requirements:
    build:
        - libgcc-ng
        - libstdcxx-ng
        - python
        - setuptools
        - cython
        - pybind11
        - zlib
    run:
        - libstdcxx-ng
        - libgcc-ng
        - _openmp_mutex
        - zlib
        - numpy >=1.11
        - atari_py 
        - gym
        - pytorch >=1.4
        - tqdm