# conda-build pkg -c default -c pytorch -c conda-forge
package:
    name: torchcule
    version: 0.1

source: 
    path: ..

requirements:
    build:
        - libgcc-ng
        - libstdcxx-ng
        - python
        - setuptools
        - cython
        - pybind11
        - zlib
    run:
        - libstdcxx-ng
        - _openmp_mutex
        - libgcc-ng
        - zlib
        - numpy >=1.11
        - gym
        - pytorch >=1.4

test:
    imports:
        - torchcule.atari
    commands:
        - python -c "from torchcule.atari import Env; env = Env('PongNoFrameskip-v4', 1); env.reset()"